name: Licence Manager
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  license-manager:
    name: License Manager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULES }}
          submodules: recursive
      - name: Checkout Library
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULES }}
          repository: 'SemioticLabs/jenkins-util.git'
          ref: 'master'
          path: '.github/shared'
          submodules: recursive
      - name: Execute Fossa
        run: |
          .github/shared/github-library/workflows/fossa-check-runs
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
